# Generated by Django 6.0.2 on 2026-02-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_buyer_first_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='buyer_first_email',
            new_name='buyer_first_email_sent_at',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='seller_first_email',
            new_name='seller_first_email_sent_at',
        ),
    ]
