# Generated by Django 6.0.2 on 2026-02-13 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_conversation_unique_together_and_more'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('product', 'buyer', 'seller')},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='products.product'),
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_sender',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_text',
        ),
    ]
