# Generated by Django 6.0.2 on 2026-02-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bacth',
            new_name='batch',
        ),
    ]
