# Generated by Django 6.0.2 on 2026-02-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_bacth_profile_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
